#!/bin/bash
# Script to remove autogenerated and environment-specific files for a clean repo
# Run this before committing or after cloning to avoid path issues

set -e

# Remove known autogenerated scripts and configs
rm -f \
  judge/judgedaemon \
  judge/domjudge-judgedaemon@.service \
  judge/create-cgroups.service \
  sql/dj_setup_database \
  misc-tools/import-contest \
  misc-tools/fix_permissions \
  misc-tools/configure-domjudge \
  misc-tools/dj_judgehost_cleanup \
  webapp/config/static.yaml \
  webapp/config/autoload.php \
  etc/domserver-static.php \
  etc/judgehost-static.php \
  etc/domjudge-fpm.conf \
  etc/nginx-conf \
  etc/nginx-conf-inner \
  etc/runguard-config.h \
  etc/sudoers-domjudge \
  etc/config.h \
  etc/apache.conf \
  judge/chroot-startstop.sh \
  misc-tools/dj_make_chroot \
  misc-tools/dj_make_chroot_docker \
  misc-tools/dj_run_chroot 

# Remove LaTeX and build artifacts
targets=(
  doc/manual/build/
  *.fls
  *.aux
  *.out
  *.pdf
  *.log
  output/
  paths.mk
  config.status
  config.log
  autom4te.cache/
)
for t in "${targets[@]}"; do
  rm -rf $t
  find . -name "$t" -exec rm -rf {} + 2>/dev/null || true
done

# Remove binary and .doctree files with hardcoded paths
find . -type f \( -name '*.doctree' -o -name '*.pickle' -o -name 'evict' -o -name 'runguard' -o -name 'runpipe' \) -delete

echo "Cleanup complete. Repo is ready for a fresh build or commit."
